language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
matrix:
  allow_failures:
  - jdk: oraclejdk9
  - jdk: oraclejdk10
  - jdk: openjdk9
  - jdk: openjdk10
  - jdk: openjdk11
before_install:
# this is a hack, so PR builds can be tested in travis
  - perl -i -0pe 's/maven[\s\{]+[^\{\}]*\}/maven { url \"https:\/\/build.shibboleth.net\/nexus\/content\/groups\/public\" \n url \"https:\/\/repo1.maven.org\/maven2\" \n jcenter() }/gms' build.gradle
